### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Yewon-Seo** [pre-commit/pre-commit-mirror-maker#140]
Hi, teams.

I tried to make a mirror repository but an error occurred.

`D:\...\pre-commit-mirrors-textlint>pre-commit-mirror pre-commit-mirrors-textlint --language node --package-name textlint --files-regex '\.md$'`

I already installed pre-commit-mirror and textlint modules, and made empty git repository and clone also.
How do I fix this problem?

Please let me reply ASAP.
Thank you.

`D:\...\pre-commit-mirrors-textlint>pre-commit-mirror pre-commit-mirrors-textlint --language node --package-name textlint --files-regex '\.md$'
Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\...\AppData\Local\Programs\Python\Python39\Scripts\pre-commit-mirror.exe\__main__.py", line 7, in <module>
  File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\pre_commit_mirror_maker\main.py", line 98, in main
    make_repo(
  File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\pre_commit_mirror_maker\make_repo.py", line 75, in make_repo
    package_versions = LIST_VERSIONS[language](name)
  File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\pre_commit_mirror_maker\languages.py", line 18, in node_get_package_versions
    output = json.loads(subprocess.check_output(cmd))
  File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 指定されたファイルが見つかりません。`

**Comment by asottile** [comment]
command not found means you need to install whatever command is missing

**Comment by asottile** [comment]
they are the same

**Comment by Yewon-Seo** [comment]
Hi, I fianlly fixed it.
This issue occurred when mirroring a repository related to node in a window environment.
It was solved with the shell = True option.

`def node_get_package_versions(package_name: str) -> list[str]:
    cmd = ('npm', 'view', package_name, '--json')
    output = json.loads(subprocess.check_output(cmd, shell=True))
    return output['versions']`

If there is no problem, I suggest adding the shell = True option.
How about that.

**Comment by asottile** [comment]
that is absolutely not a fix, no
